**Пример 1.2.1**
Создать массив 5х2. Создать массив 5х2. Вывести все занчения массива, значения элемента с индексом (3,1) и второй столбец. Индексация начинается с нуля. 

In [6]:
import numpy as np

x = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
print(x)
print(x[3][1])
print(x[1])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
8
[3 4]


**Пример 1.2.2** 
1. Создать вектор размера 10, заполненный единицами.
2. Создать вектор размера 10, заполненный заданным числом.
3. Создать вектор размера 10, заполненными заданным числом.
4. Созданный вектор со значениями от 10 до 19

In [7]:
a = np.zeros(10)
b = np.ones(10)
c = np.full(10, 5)
d = np.arange(10, 20)
print(a, "\n", b, "\n", c, "\n", d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 
 [5 5 5 5 5 5 5 5 5 5] 
 [10 11 12 13 14 15 16 17 18 19]


**Пример 1.2.3**
Создать массив 10х10 со случайными значениями, найти минимум, максимум и среднее занчение.

In [10]:
Z = np.random.random((10, 10))
Zmin, Zmax, Zmean = Z.min(), Z.max(), Z.mean()
print(Zmin, Zmax, Zmean)

0.039672978004887005 0.9951399075834003 0.4894038368904278


**Пример 1.2.4**
Задание матрицу размерности 5 на 5 и поменять 2 строки в матрице местами. 

In [12]:
A = np.arange(25).reshape(5, 5)
print(A)
A[[0, 1]] = A[[1, 0]]
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


**Пример 1.2.5**
Выяснить результат следующих выражений:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1

In [10]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


**Пример 1.2.6**
Отсоритровать массив.

In [11]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(np.sort(arr))

[1 2 3 4 5 6 7 8]


**Задание 1.3.1**
Создать 8х8 матрицу и заполнить её в шахматном порядке нулями и единицами. 

In [23]:
arr = np.zeros((8, 8))
for i in range(0, 8):
    for y in range(0, 8):
        if y % 2 == 1:
            arr[i][y] = 1
        else:
            arr[i][y] = 0
print(arr)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


**Задание 1.3.2** 
Создать 5х5 матрицу со значениями в строках от 0 до 4. 
Для создания необходимо использовать функцию arrange.

In [11]:
import numpy as np


A = np.tile(np.arange(5), (5,1))
print(A)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


**Задание 1.3.3** 
Создать массив 3x3 со случайными значениями.

In [13]:
import numpy as np


arr = np.random.random((3, 3))     
print(arr)

[[0.62183789 0.5874527  0.83657497]
 [0.17165014 0.50154343 0.59494042]
 [0.41583437 0.03736301 0.56261075]]


**Задание 1.3.4**
Создать матрицу с 0 внутри, и 1 на границах.

In [15]:
import numpy as np


def first_one(arr : list):
    for i in range(0, 1):
        for y in  range(0, len(arr)):
            arr[i][y] = 1
            
    for i in range(len(arr) - 1, len(arr)):
        for y in  range(0, len(arr)):
            arr[i][y] = 1
            
    for i in range(0, len(arr)):
        for y in  range(0, 1):
            arr[i][y] = 1
            
    for i in range(0, len(arr)):
        for y in  range(len(arr) - 1, len(arr)):
            arr[i][y] = 1
            
    return arr

def main(n : int) -> list:
    arr = np.zeros((n, n))
    first_one(arr)
    return arr

if __name__ == '__main__':
    print(main(10000))


[[1. 1. 1. ... 1. 1. 1.]
 [1. 0. 0. ... 0. 0. 1.]
 [1. 0. 0. ... 0. 0. 1.]
 ...
 [1. 0. 0. ... 0. 0. 1.]
 [1. 0. 0. ... 0. 0. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


**Задание 1.3.5**
Создайте массив и отсортируйте его по убыванию.

In [27]:
from random import randint
from math import sqrt

def SortedReverse(arr : list)->list:
    for i in range(0, len(arr)):
        for y in range((len(arr) - i - 1)):
            if arr[y] < arr[y + 1]:
                arr[y], arr[y+1] = arr[y+1], arr[y]
    
    return arr

def CreateArray(n : int)->list:
    arr = []
    
    for i in range(n):
        s = randint(0, n)
        arr.append(s)
    
    return arr

if __name__ == '__main__':
    print(SortedReverse(CreateArray(100)))

[99, 94, 93, 91, 90, 89, 89, 89, 88, 88, 88, 87, 87, 86, 85, 85, 84, 83, 82, 81, 79, 79, 79, 78, 76, 76, 76, 76, 74, 73, 73, 72, 72, 71, 70, 70, 69, 68, 65, 65, 62, 61, 61, 61, 60, 60, 60, 59, 54, 54, 54, 54, 51, 49, 49, 49, 48, 43, 43, 43, 40, 39, 38, 37, 37, 36, 33, 32, 31, 30, 30, 29, 28, 28, 27, 26, 24, 24, 23, 22, 22, 21, 20, 19, 17, 17, 13, 12, 10, 10, 7, 7, 6, 6, 4, 4, 2, 1, 0, 0]


**Задание 1.3.6**
Создайте матрицу, выведите форму, размер и размерность.

In [29]:
import numpy as np


matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


print(f"Форма матрицы: {matrix.shape}")

print(f"\nРазмер матрицы: {matrix.size}")

print(f"\nРазмерность матрицы: {matrix.ndim}")


Форма матрицы: (3, 3)

Размер матрицы: 9

Размерность матрицы: 2


**2.2.1 Пример**
Создать Series из списка Python, словаря Python, и массива Numpy
(установить буквенные метки для последнего).

In [30]:
import pandas as pd


lst = [1, 2, 3, 4, 5]
d = {'a' : 1, 'b' : 2, 'c' : 3}
ndarr = np.array([1, 2, 3, 4, 5])

s1 = pd.Series(lst)
s2 = pd.Series(d)
s3 = pd.Series(ndarr, ['a', 'b', 'c', 'd', 'e'])

print(s1)
print(s2)
print(s3)

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int32


**2.2.2 Пример**
Дано два Series. Напечатать их первые элементы и все элементы после третьего (во втором фрейме).

In [2]:
import pandas as pd


s1 = pd.Series([1, 2, 3, 4, 5], ['a', 'b', 'c', 'd', 'e'])
s2 = pd.Series([5, 4, 3, 2, 1])
print(s1['a'])
print(s2[0])
print(s2[3:])

1
5
3    2
4    1
dtype: int64


**2.2.3 Пример**
Создать новый фрейм данных.

In [3]:
import pandas as pd


dataframe = pd.DataFrame()
dataframe['Имя'] = ['Джеки Джексон', 'Стивен Стивенсон']
dataframe['Возраст'] = [38, 25]
dataframe['Водитель'] = [True, False]
dataframe


Имя  Возраст  Водитель
0     Джеки Джексон       38      True
1  Стивен Стивенсон       25     False

**2.2.4 Пример**
Загрузите фрейм данных по сслыке:

In [13]:
import pandas as pd

url = 'https://raw.githubusercontent.com/MainakRepositor/Datasets/master/F1/results.csv'
    
dataframe = pd.read_csv(url)
dataframe.head(10)

resultId  raceId  driverId  constructorId  number  grid  position  \
0         1      18         1              1    22.0     1       1.0   
1         2      18         2              2     3.0     5       2.0   
2         3      18         3              3     7.0     7       3.0   
3         4      18         4              4     5.0    11       4.0   
4         5      18         5              1    23.0     3       5.0   
5         6      18         6              3     8.0    13       6.0   
6         7      18         7              5    14.0    17       7.0   
7         8      18         8              6     1.0    15       8.0   
8         9      18         9              2     4.0     2       NaN   
9        10      18        10              7    12.0    18       NaN   

  positionText  positionOrder  points  laps     time  milliseconds  \
0            1              1    10.0    58  34:50.6     5690616.0   
1            2              2     8.0    58    5.478     5696094.0   
2            3              3     6.0    58    8.163     5698779.0   
3            4              4     5.0    58   17.181     5707797.0   
4            5              5     4.0    58   18.014     5708630.0   
5            6              6     3.0    57      NaN           NaN   
6            7              7     2.0    55      NaN           NaN   
7            8              8     1.0    53      NaN           NaN   
8            R              9     0.0    47      NaN           NaN   
9            R             10     0.0    43      NaN           NaN   

   fastestLap  rank fastestLapTime fastestLapSpeed  statusId  
0        39.0   2.0        01:27.5           218.3         1  
1        41.0   3.0        01:27.7         217.586         1  
2        41.0   5.0        01:28.1         216.719         1  
3        58.0   7.0        01:28.6         215.464         1  
4        43.0   1.0        01:27.4         218.385         1  
5        50.0  14.0        01:29.6         212.974        11  
6        22.0  12.0        01:29.5         213.224         5  
7        20.0   4.0        01:27.9          217.18         5  
8        15.0   9.0        01:28.8           215.1         4  
9        23.0  13.0        01:29.6         213.166         3

**2.2.5 Пример**
Пронализировать характеристики фрейма данны

In [18]:
import pandas as pd


url = 'https://raw.githubusercontent.com/MainakRepositor/Datasets/master/F1/results.csv'
    
dataframe = pd.read_csv(url)
# dataframe.head(2)
dataframe.tail(3)
# dataframe.shape
# dataframe.describe()

resultId  raceId  driverId  constructorId  number  grid  position  \
23774     23779     988       840              3    18.0    15      18.0   
23775     23780     988       832              4    55.0    12       NaN   
23776     23781     988       817              9     3.0     4       NaN   

      positionText  positionOrder  points  laps time  milliseconds  \
23774           18             18     0.0    54  NaN           NaN   
23775            R             19     0.0    31  NaN           NaN   
23776            R             20     0.0    20  NaN           NaN   

       fastestLap  rank fastestLapTime fastestLapSpeed  statusId  
23774        52.0   6.0        01:42.3         195.402        11  
23775        26.0  14.0        01:43.4          193.41        36  
23776        13.0  12.0        01:42.8         194.579         9

**2.6.6 Пример**
Выберите индивидуальные данные или срезы фрейма данных

In [19]:
import pandas as pd


url = 'https://raw.githubusercontent.com/MainakRepositor/Datasets/master/F1/results.csv'
    
dataframe = pd.read_csv(url)
dataframe.iloc[1:4]

resultId  raceId  driverId  constructorId  number  grid  position  \
1         2      18         2              2     3.0     5       2.0   
2         3      18         3              3     7.0     7       3.0   
3         4      18         4              4     5.0    11       4.0   

  positionText  positionOrder  points  laps    time  milliseconds  fastestLap  \
1            2              2     8.0    58   5.478     5696094.0        41.0   
2            3              3     6.0    58   8.163     5698779.0        41.0   
3            4              4     5.0    58  17.181     5707797.0        58.0   

   rank fastestLapTime fastestLapSpeed  statusId  
1   3.0        01:27.7         217.586         1  
2   5.0        01:28.1         216.719         1  
3   7.0        01:28.6         215.464         1

**2.2.7 Пример**
Требуется отобрать строки фрейма данных на основе некоторого 
условия. Необходимо сформировать новый фрейм данных из пассажиров 
первого класса.

In [21]:
import pandas as pd


url = 'https://raw.githubusercontent.com/MainakRepositor/Datasets/master/F1/results.csv'
    
dataframe = pd.read_csv(url)
dataframe[dataframe['constructorId'] == 2].head(5)

resultId  raceId  driverId  constructorId  number  grid  position  \
1          2      18         2              2     3.0     5       2.0   
8          9      18         9              2     4.0     2       NaN   
23        24      19         9              2     4.0     4       2.0   
27        28      19         2              2     3.0     5       6.0   
46        47      20         9              2     4.0     1       3.0   

   positionText  positionOrder  points  laps    time  milliseconds  \
1             2              2     8.0    58   5.478     5696094.0   
8             R              9     0.0    47     NaN           NaN   
23            2              2     8.0    56   19.57     5498125.0   
27            6              6     3.0    56  49.833     5528388.0   
46            3              3     6.0    57   4.998     5471968.0   

    fastestLap  rank fastestLapTime fastestLapSpeed  statusId  
1         41.0   3.0        01:27.7         217.586         1  
8         15.0   9.0        01:28.8           215.1         4  
23        39.0   6.0        01:35.9         208.033         1  
27        55.0   1.0        01:35.4         209.244         1  
46        55.0   5.0        01:33.8         207.765         1

**2.3.1 Задание**
Найдите евклидово расстояние между двумя Series (точками) a и b, не используя встроенную формулу.

In [26]:
import math


def euclidean_distance(a, b):
    x1, y1 = a
    x2, y2 = b
    return math.sqrt((x1 - x2)**2 + (y1 - y2)**2)

a = (2, 4)
b = (5, 8)

distance = euclidean_distance(a, b)

print(f"Евклидово расстояние между точками {a} и {b} равно {distance}")

Евклидово расстояние между точками (2, 4) и (5, 8) равно 5.0


**2.3.2 Задание**
Найдите в Интернете ссылку на любой csv файл и сформируйте из него 
фрейм данных (например, коллекцию фреймов данных можно найти 
здесь: https://github.com/akmand/datasets)

In [35]:
import pandas as pd


url = 'https://raw.githubusercontent.com/MainakRepositor/Datasets/master/F1/qualifying.csv'

dataframe = pd.read_csv(url)
dataframe.head(10)


qualifyId  raceId  driverId  constructorId  number  position        q1  \
0          1      18         1              1      22         1  1:26.572   
1          2      18         9              2       4         2  1:26.103   
2          3      18         5              1      23         3  1:25.664   
3          4      18        13              6       2         4  1:25.994   
4          5      18         2              2       3         5  1:25.960   
5          6      18        15              7      11         6  1:26.427   
6          7      18         3              3       7         7  1:26.295   
7          8      18        14              9       9         8  1:26.381   
8          9      18        10              7      12         9  1:26.919   
9         10      18        20              5      15        10  1:26.702   

         q2        q3  
0  1:25.187  1:26.714  
1  1:25.315  1:26.869  
2  1:25.452  1:27.079  
3  1:25.691  1:27.178  
4  1:25.518  1:27.236  
5  1:26.101  1:28.527  
6  1:26.059  1:28.687  
7  1:26.063  1:29.041  
8  1:26.164  1:29.593  
9  1:25.842       NaN

**2.3.3 Задание**
Проделайте с получившемся из предыдущего задания фреймом данных 
те же действия, что и в примерах 2.2.5-2.2.7

In [41]:
import pandas as pd


url = 'https://raw.githubusercontent.com/MainakRepositor/Datasets/master/F1/qualifying.csv'

dataframe = pd.read_csv(url)
# dataframe.head(2)
# dataframe.tail(3)
# dataframe.shape
# dataframe.describe()
# dataframe.iloc[1:4]
dataframe[dataframe['raceId'] == 10].head(5)

qualifyId  raceId  driverId  constructorId  number  position        q1  \
7513       7537     988       836             15      94        18  1:39.930   
7514       7538     988       828             15       9        19  1:39.994   
7515       7539     988       843              5      28        20  1:40.471   

       q2   q3  
7513  NaN  NaN  
7514  NaN  NaN  
7515  NaN  NaN

**3.2.1 Пример**
Прошкалируйте числовой признак в диапазон между двумя значениями

In [43]:
import numpy as np
from sklearn import preprocessing


feature = np.array([[-500.5], [-100.1], [100.1], [900.9]])

minmax_scale = preprocessing.MinMaxScaler(feature_range = (0, 1))

scaled_feature = minmax_scale.fit_transform(feature)

scaled_feature

array([[0.        ],
       [0.28571429],
       [0.42857143],
       [1.        ]])

**3.2.2 Пример**
Преобразуйте признак, чтобы он имел среднее значение 0 и стандартное 
отклонение 1.

In [45]:
import numpy as np
from sklearn import preprocessing


x = np.array([[-1000.1], [-200.2], [500.5], [600.6], [9000.9]])

scaler = preprocessing.StandardScaler()

standardized = scaler.fit_transform(x)

standardized

print(f"Среднее: {round(standardized.mean())}")
print(f"Стандартное отклонение: {standardized.std()}")

Среднее: 0
Стандартное отклонение: 1.0


**3.2.2 Пример**
Дан фрейм данных 
dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
 'B':[103.02,107.26,110.35,114.23,114.68],
 'C':['big','small','big','small','small']})
Необходимо масштабировать его числовые столбцы.

In [46]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler


scaler = MinMaxScaler()
dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
 'B':[103.02,107.26,110.35,114.23,114.68],
 'C':['big','small','big','small','small']})

dfTest[['A', 'B']] = scaler.fit_transform(dfTest[['A', 'B']])
dfTest

A         B      C
0  0.000000  0.000000    big
1  0.926219  0.363636  small
2  0.935335  0.628645    big
3  1.000000  0.961407  small
4  0.938495  1.000000  small

**3.3.2 Задание**
Загрузить фрейм данных по ссылке:
https://raw.githubusercontent.com/akmand/datasets/master/iris.csv.
Необходимо выполнить нормализацию первого числового признака 
(sepal_length_cm) с использованием минимаксного преобразования, а 
второго (sepal_width_cm) с задействованием z-масштабирования

In [50]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler


url = "https://raw.githubusercontent.com/akmand/datasets/master/iris.csv"
data = pd.read_csv(url)

minmaxscaler = MinMaxScaler()
scaler = StandardScaler()

# Нормализация первого признака (sepal_length_cm) с использованием минимаксного преобразования
data['sepal_length_cm'] = minmaxscaler.fit_transform(data[['sepal_length_cm']])

# Нормализация второго признака (sepal_width_cm) с использованием z-масштабирования
data['sepal_width_cm'] = scaler.fit_transform(data[['sepal_width_cm']])

data

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0           0.222222        1.032057              1.4             0.2   
1           0.166667       -0.124958              1.4             0.2   
2           0.111111        0.337848              1.3             0.2   
3           0.083333        0.106445              1.5             0.2   
4           0.194444        1.263460              1.4             0.2   
..               ...             ...              ...             ...   
145         0.666667       -0.124958              5.2             2.3   
146         0.555556       -1.281972              5.0             1.9   
147         0.611111       -0.124958              5.2             2.0   
148         0.527778        0.800654              5.4             2.3   
149         0.444444       -0.124958              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]